"""initial schema

Revision ID: 191e1f381995
Revises: 
Create Date: 2026-08-29 22:52:43.531575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '191e1f381995'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('permission_mode', sa.String(length=32), nullable=False),
    sa.Column('repo_refresh_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('mcp_servers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skills',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agent_mcp_servers',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('mcp_server_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'mcp_server_id')
    )
    op.create_index(op.f('ix_agent_mcp_servers_mcp_server_id'), 'agent_mcp_servers', ['mcp_server_id'], unique=False)
    op.create_table('agent_repositories',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('auth_type', sa.String(length=32), nullable=False),
    sa.Column('auth_credential', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_commit', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_repositories_agent_id'), 'agent_repositories', ['agent_id'], unique=False)
    op.create_table('agent_skills',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'skill_id')
    )
    op.create_index(op.f('ix_agent_skills_skill_id'), 'agent_skills', ['skill_id'], unique=False)
    op.create_table('conversations',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.create_table('sdk_sessions',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sdk_sessions_agent_id'), 'sdk_sessions', ['agent_id'], unique=False)
    op.create_table('workspace_snapshots',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('repo_snapshot_object_key', sa.String(length=512), nullable=True),
    sa.Column('repo_snapshot_version', sa.Integer(), nullable=False),
    sa.Column('repo_snapshot_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_snapshot_object_key', sa.String(length=512), nullable=True),
    sa.Column('output_snapshot_version', sa.Integer(), nullable=False),
    sa.Column('output_snapshot_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_snapshot_update_source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_snapshots')
    op.drop_index(op.f('ix_sdk_sessions_agent_id'), table_name='sdk_sessions')
    op.drop_table('sdk_sessions')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_agent_skills_skill_id'), table_name='agent_skills')
    op.drop_table('agent_skills')
    op.drop_index(op.f('ix_agent_repositories_agent_id'), table_name='agent_repositories')
    op.drop_table('agent_repositories')
    op.drop_index(op.f('ix_agent_mcp_servers_mcp_server_id'), table_name='agent_mcp_servers')
    op.drop_table('agent_mcp_servers')
    op.drop_table('skills')
    op.drop_table('mcp_servers')
    op.drop_table('agents')
    # ### end Alembic commands ###
