"""mcp server encrypted config

Revision ID: 4a51fbaabd44
Revises: d9597aafe1c9
Create Date: 2026-08-30 12:17:57.193095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a51fbaabd44'
down_revision: Union[str, None] = 'd9597aafe1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('config_encrypted', sa.Text(), nullable=False))
    op.drop_column('mcp_servers', 'config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('mcp_servers', 'config_encrypted')
    # ### end Alembic commands ###
