"""agent repository last sync error

Revision ID: 7c2a4e1f9b3d
Revises: dbf10ea831f1
Create Date: 2026-08-30 18:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2a4e1f9b3d'
down_revision: Union[str, None] = 'dbf10ea831f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_repositories', sa.Column('last_sync_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_repositories', 'last_sync_error')
    # ### end Alembic commands ###
