"""agent description

Revision ID: dbf10ea831f1
Revises: 4a51fbaabd44
Create Date: 2026-08-30 17:22:12.642601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf10ea831f1'
down_revision: Union[str, None] = '4a51fbaabd44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'description')
    # ### end Alembic commands ###
